# Generated by Django 4.1.13 on 2024-05-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'ordering': ['-creado'], 'verbose_name': 'orden', 'verbose_name_plural': 'ordenes'},
        ),
    ]
